### PR TITLE
Returning NULL instead of exceptions

### PR DESCRIPTION
**Pull request by ddevault**
I changed this to follow the standard of XDocument and others like it.  It's much easier to check for null than to write an entire try/catch for queries.

### CODE REVIEW

**Comment by aphistic** [comment]
Thanks! I'll get this merged this weekend and write some new tests for it.

**Comment by aphistic** [comment]
Hey, in your most recent commit (adding Int Array tags), it looks like you're missing the NbtIntArray.cs file. Would you be able to add that?

**Comment by ddevault** [comment]
Added those files, thanks for waiting.

**Comment by ddevault** [comment]
ping

**Pull request closed without merging**
